name: manual-cron

on:
  schedule:
    - cron: '30 23 * * *'  # 5:00 AM IST (runs at 23:30 UTC)
  workflow_dispatch:  # Enables manual triggering

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
