name: 18jul Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      branch_to_deploy:
        description: 'Branch to deploy'
        required: true
      customer:
        description: 'Customer to deploy'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  runtimeInfo: 
    name: Print Runtime Environment details
    runs-on: self-hosted
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.branch_name }}

      - name: Print deployment details
        run: |
          echo "Branch to deploy: ${{ github.event.inputs.branch_to_deploy }}"
          echo "Customer: ${{ github.event.inputs.customer }}"
