name: Run on Selected Branch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run this workflow on'
        required: true
        default: 'main'

jobs:
  run-on-input-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Selected Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Print Branch Name
        run: echo "Running job on branch: ${{ github.event.inputs.target_branch }}"
