# .github/workflows/manual-run.yaml
name: Manual Job Trigger

on:
  workflow_dispatch:  # 👈 Enables manual trigger via GitHub UI

jobs:
  run-manually:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, Akash! This job was triggered manually."
