# .github/workflows/manual-name-input.yaml
name: Manual Name Input Workflow

on:
  workflow_dispatch:
    inputs:
      person_name:
        description: 'Enter your name'
        required: true
        default: 'Ankit'

jobs:
  greet-person:
    runs-on: ubuntu-latest
    steps:
      - name: Greet by name
        run: echo "Hello, ${{ github.event.inputs.person_name }}!"
