name: Five Minute Hello World

on:
  schedule:
    #- cron: "*/5 * * * *"
    - cron: '35 15 * * *'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
