name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - warning
          - info
          - error
      tags:
        description: 'Test scenario tags'
        required: true
