name: Run hel.sh Script

on:
  repository_dispatch:
    types: run-hel-script

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v3

      - name: Run hel.sh
        run: |
          chmod +x ./hel.sh  # Ensure the script is executable
          ./hel.sh            # Execute the script
