name: Trigger Repo B GitHub workflow
on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"  # Command to print Hello World

      - name: List files
        run: ls -la  # Debugging step to list files
      

      - name: Make hel.sh executable
        run: chmod +x ../../hel.sh  # Ensure the script has execute permissions

      - name: Run hel.sh
        run: ../../hel.sh  # Execute the hel.sh script

